import type { Metadata } from "next";
import "./globals.css";
import { Sidebar, SidebarButton } from "@/components/sidebar";
import { CompassIcon, HomeIcon, Layers } from "lucide-react";
import { Header } from "@/components/header";
import { Roboto } from "next/font/google";

const RobotoFont = Roboto({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Bata Shoes | Quality Brands",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${RobotoFont.className} h-screen antialiased`}>
        <Header />

        <section className="flex relative h-screen">
          <Sidebar>
            <SidebarButton>
              <HomeIcon strokeWidth={1.25} size={24} />
              Home
            </SidebarButton>
            <SidebarButton>
              <CompassIcon strokeWidth={1.25} size={24} />
              Explore
            </SidebarButton>
            <SidebarButton>
              <Layers strokeWidth={1.25} size={24} />
              Subscriptions
            </SidebarButton>
          </Sidebar>
          <div className="flex-1 h-fit bg-[var(--black)]">{children}</div>
        </section>
      </body>
    </html>
  );
}
